backend:
  name: git-gateway
  branch: main
  
media_folder: "src/assets/img/"
public_folder: "/assets/img/"

publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Blog" 
    folder: "src/blog"
    media_folder: "img/"
    public_folder: "/blog/img/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Kategoria", name: "tags", widget: "list"}
      - {label: "Obrazek", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "works"
    label: "Realizacje"
    folder: "src/realizacje"
    media_folder: "img/"
    public_folder: "/realizacje/img/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/case.njk"}
      - {label: "Klient", name: "client", widget: "string"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Kategoria", name: "category", widget: "list"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Thumb", name: "thumbnail", widget: "image"}
      - {label: "Mockup", name: "imageMain", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}


 # Faq
  - label: "FAQ"
    name: "faq"
    folder: "src/faq"
    create: true
    fields:
      - {label: "Pytanie", name: "title", widget: "string"}
      - {label: "Odpowiedź", name: "answer", widget: "markdown"}